(* fixtures.sml -- GENERATED by bin/gen_fixtures.py. Do not edit.
   A unit quad (two triangles) in OBJ/MTL/PLY forms. The binary PLY is
   packed with python struct to validate the binary reader. *)

structure Fixtures =
struct
  fun bytes l = Word8Vector.fromList l

  val obj_quad = "# a unit quad\nv 0 0 0\nv 1 0 0\nv 1 1 0\nv 0 1 0\nvt 0 0\nvt 1 0\nvt 1 1\nvt 0 1\nvn 0 0 1\n# quad face, will be triangulated\nf 1/1/1 2/2/1 3/3/1 4/4/1\n"

  val obj_neg = "v 0 0 0\nv 1 0 0\nv 0 1 0\nvn 0 0 1\nf -3//1 -2//1 -1//1\n"

  val mtl = "# materials\nnewmtl red\nKa 0.1 0.0 0.0\nKd 0.8 0.1 0.1\nKs 1.0 1.0 1.0\n\nnewmtl green\nKd 0.1 0.7 0.2\n"

  val ply_ascii = bytes [0wx70,0wx6C,0wx79,0wx0A,0wx66,0wx6F,0wx72,0wx6D,0wx61,0wx74,0wx20,0wx61,0wx73,0wx63,0wx69,0wx69,0wx20,0wx31,0wx2E,0wx30,0wx0A,0wx65,0wx6C,0wx65,0wx6D,0wx65,0wx6E,0wx74,0wx20,0wx76,0wx65,0wx72,0wx74,0wx65,0wx78,0wx20,0wx34,0wx0A,0wx70,0wx72,0wx6F,0wx70,0wx65,0wx72,0wx74,0wx79,0wx20,0wx66,0wx6C,0wx6F,0wx61,0wx74,0wx20,0wx78,0wx0A,0wx70,0wx72,0wx6F,0wx70,0wx65,0wx72,0wx74,0wx79,0wx20,0wx66,0wx6C,0wx6F,0wx61,0wx74,0wx20,0wx79,0wx0A,0wx70,0wx72,0wx6F,0wx70,0wx65,0wx72,0wx74,0wx79,0wx20,0wx66,0wx6C,0wx6F,0wx61,0wx74,0wx20,0wx7A,0wx0A,0wx65,0wx6C,0wx65,0wx6D,0wx65,0wx6E,0wx74,0wx20,0wx66,0wx61,0wx63,0wx65,0wx20,0wx31,0wx0A,0wx70,0wx72,0wx6F,0wx70,0wx65,0wx72,0wx74,0wx79,0wx20,0wx6C,0wx69,0wx73,0wx74,0wx20,0wx75,0wx63,0wx68,0wx61,0wx72,0wx20,0wx69,0wx6E,0wx74,0wx20,0wx76,0wx65,0wx72,0wx74,0wx65,0wx78,0wx5F,0wx69,0wx6E,0wx64,0wx69,0wx63,0wx65,0wx73,0wx0A,0wx65,0wx6E,0wx64,0wx5F,0wx68,0wx65,0wx61,0wx64,0wx65,0wx72,0wx0A,0wx30,0wx20,0wx30,0wx20,0wx30,0wx0A,0wx31,0wx20,0wx30,0wx20,0wx30,0wx0A,0wx31,0wx20,0wx31,0wx20,0wx30,0wx0A,0wx30,0wx20,0wx31,0wx20,0wx30,0wx0A,0wx34,0wx20,0wx30,0wx20,0wx31,0wx20,0wx32,0wx20,0wx33,0wx0A]

  val ply_binary = bytes [0wx70,0wx6C,0wx79,0wx0A,0wx66,0wx6F,0wx72,0wx6D,0wx61,0wx74,0wx20,0wx62,0wx69,0wx6E,0wx61,0wx72,0wx79,0wx5F,0wx6C,0wx69,0wx74,0wx74,0wx6C,0wx65,0wx5F,0wx65,0wx6E,0wx64,0wx69,0wx61,0wx6E,0wx20,0wx31,0wx2E,0wx30,0wx0A,0wx65,0wx6C,0wx65,0wx6D,0wx65,0wx6E,0wx74,0wx20,0wx76,0wx65,0wx72,0wx74,0wx65,0wx78,0wx20,0wx34,0wx0A,0wx70,0wx72,0wx6F,0wx70,0wx65,0wx72,0wx74,0wx79,0wx20,0wx66,0wx6C,0wx6F,0wx61,0wx74,0wx20,0wx78,0wx0A,0wx70,0wx72,0wx6F,0wx70,0wx65,0wx72,0wx74,0wx79,0wx20,0wx66,0wx6C,0wx6F,0wx61,0wx74,0wx20,0wx79,0wx0A,0wx70,0wx72,0wx6F,0wx70,0wx65,0wx72,0wx74,0wx79,0wx20,0wx66,0wx6C,0wx6F,0wx61,0wx74,0wx20,0wx7A,0wx0A,0wx65,0wx6C,0wx65,0wx6D,0wx65,0wx6E,0wx74,0wx20,0wx66,0wx61,0wx63,0wx65,0wx20,0wx31,0wx0A,0wx70,0wx72,0wx6F,0wx70,0wx65,0wx72,0wx74,0wx79,0wx20,0wx6C,0wx69,0wx73,0wx74,0wx20,0wx75,0wx63,0wx68,0wx61,0wx72,0wx20,0wx69,0wx6E,0wx74,0wx20,0wx76,0wx65,0wx72,0wx74,0wx65,0wx78,0wx5F,0wx69,0wx6E,0wx64,0wx69,0wx63,0wx65,0wx73,0wx0A,0wx65,0wx6E,0wx64,0wx5F,0wx68,0wx65,0wx61,0wx64,0wx65,0wx72,0wx0A,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx80,0wx3F,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx80,0wx3F,0wx00,0wx00,0wx80,0wx3F,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx00,0wx80,0wx3F,0wx00,0wx00,0wx00,0wx00,0wx04,0wx00,0wx00,0wx00,0wx00,0wx01,0wx00,0wx00,0wx00,0wx02,0wx00,0wx00,0wx00,0wx03,0wx00,0wx00,0wx00]
end
